// UI 文言（spec §6）。ここと index.html の <title> 以外に文言を書かない
export const COPY = {
  viewLabel: "表示",
  groupSubject: "主題",
  groupLane: "国・地域",
  subjectRegime: "国家・体制",
  subjectGovernment: "政権",
  subjectMonarch: "君主",
  subjectLeader: "首相・大統領など",
  orientationLabel: "向き",
  orientationVertical: "縦",
  orientationHorizontal: "横",
  timelineLabel: "年表",
  present: "現在",
  periodSeparator: "、",
  loading: "読み込み中…",
  loadError: "年表のデータを読み込めませんでした。ページを再読み込みしてください。",
  panelLabel: "出典",
  sectionSources: "出典",
  sectionPeriod: "期間",
  sectionMonarch: "在位",
  sectionLeader: "在任",
  noteMark: "※",
  close: "閉じる",
  newTab: "（新しいタブで開きます）",
} as const;
