name: APM update
on:
  schedule:
    - cron: "0 0 * * *" # 毎日 9:00（日本時間）
  workflow_dispatch:
jobs:
  update:
    uses: akihiro-tj/house-rules/.github/workflows/apm-update.yml@main
    secrets: inherit
